### PR TITLE
Add option to post full RSS item body

### PR DESCRIPTION
**Pull request by ldidry**
The database will be automatically updated with a new column 'body'.

The counterpart of this commit is that it makes the database heavier (but it should not impact performances).

### CODE REVIEW

**Review by rev138 — APPROVED** [review]
Looks good, Ididry. Thanks!

**Comment by trebmuh** [comment]
Hi @ldidry and @rev138 . It looks like a great addition!
I've updated it, and it tells me "What string to format? at ./pod_feeder.pl line 369.", whatever if I'm using it with the `--body content:encoded` or the `--body description` option.
Am I doing something wrong or did I forget something ?

**Comment by ldidry** [comment]
@trebmuh just `--body`: it will choose `description` by default and replace it by `content:encoded` if present (I used my own feed for tests: https://fiat-tux.fr/feed)

What is the URL of your feed? It may be different (RSS vs ATOM for example).

**Comment by trebmuh** [comment]
@ldidry : OK, I replaced it by  just `--body` and I'll see how it goes with the next refresh (it's run as a cron job). The URL feed is https://librazik.tuxfamily.org/dotclear/blog/?feed/atom . I'll keep you in the loop later today.

**Comment by ldidry** [comment]
According to your feed, I think it won't work. Add
```
$body = HTML::FormatMarkdown->format_from_string($item->{'content'}, rm => 100000) if ($item->{'content'});
```

under [line 364](https://github.com/rev138/pod_feeder/blob/master/pod_feeder.pl#L364).

**Comment by trebmuh** [comment]
@ldidry : I made the change you suggested:
```
my $body = HTML::FormatMarkdown->format_from_string($item->{'description'}, rm => 100000);
$body    = HTML::FormatMarkdown->format_from_string($item->{'content:encoded'}, rm => 100000) if ($item->{'content:encoded'});
$body    = HTML::FormatMarkdown->format_from_string($item->{'content'}, rm => 100000) if ($item->{'content'});
```
but there is no change I can see. I still get `What string to format? at ./pod_feeder.pl line 369.`

**Comment by trebmuh** [comment]
@ldidry : ping

**Pull request merged**
